[package]
name = "fluvio-cms"
version = "0.0.0"
edition = "2021"
description = "A content management system CLI for fluvio.io"
publish = false


[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }