name: Hugo broken link check

on:
  pull_request:
    branches:
      - master

jobs:
  broken-link-check:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml
