name: Hugo broken link check

on:
  pull_request:
    branches:
      - master

jobs:
  broken-link-check:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.97.3"
          extended: true
      - name: Build
        run: hugo --verbose --buildDrafts --cleanDestinationDir --buildFuture --baseURL http://localhost
      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml
