name: Check CLI help

permissions:
  contents: read

concurrency:
  group: cli-help-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - staging
      - trying
  pull_request:
    branches: [master]
  workflow_dispatch:
  # TODO: Add schedule to check against latest

jobs:
  cli-help:
    runs-on: ubuntu-latest
    steps:
      - name: Install Fluvio CLI
        run: |
          curl -fsS https://packages.fluvio.io/v1/install.sh | bash
          echo "$HOME/.fluvio/bin" >> $GITHUB_PATH
          fluvio install smdk
      - name: Run CLI help text script
        run: make update-cli-help
      # This step will evaluate the repo status and report the change
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      # You can now access a variable indicating if there have been changes
      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: echo "Changes exist"
