name: Test client examples

permissions:
  contents: read

concurrency:
  group: examples-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - staging
      - trying
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  K3D_VERSION: v5.4.1

jobs:
  examples:
    name: Run all client examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client-type:
          - rust
          - python
          - node
          - java

    steps:
      - name: Skip label check
        id: skip_label_check
        uses: agilepathway/label-checker@v1.2.7
        with:
          all_of: CI:bors-skip-client-examples
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          allow_failure: true

      - uses: actions/checkout@v3
        if: steps.skip_label_check.outputs.label_check != 'success'

      - uses: actions/checkout@v3
        if: steps.skip_label_check.outputs.label_check != 'success'
        with:
          repository: infinyon/fluvio
          path: fluvio-repo
      - name: Setup K3d
        if: steps.skip_label_check.outputs.label_check != 'success'
        run: curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | TAG=${{ env.K3D_VERSION }} bash
      - name: Create K3d cluster
        run: |
          ./fluvio-repo/k8-util/cluster/reset-k3d.sh

      - name: Sleep 20 to ensure k3d cluster is ready
        if: steps.skip_label_check.outputs.label_check != 'success'
        run: sleep 20
      - name: Install Fluvio Local Cluster
        if: steps.skip_label_check.outputs.label_check != 'success'
        uses: infinyon/fluvio@master
        with:
          cluster-type: local
          version: latest

      # Ensure cluster is started
      - name: Ensure Fluvio Cluster is up
        if: steps.skip_label_check.outputs.label_check != 'success'
        run: |
          make cluster-verify

      - name: Build and test clients
        if: steps.skip_label_check.outputs.label_check != 'success'
        uses: nick-fields/retry@v2.8.2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            make run-client-example-${{ matrix.client-type }}
          on_retry_command: |
            fluvio cluster delete
            fluvio cluster start --local --image-version latest

  # Job that follows the success of all required jobs in this workflow.
  # Used by Bors to detect that all required jobs have completed successfully
  done:
    name: Pass client examples
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: examples
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo "Done!"
