name: Test client examples

permissions:
  contents: read

concurrency:
  group: examples-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - staging
      - trying
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  examples:
    name: Run all client examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client-type:
          - rust
          - python
          - node
          - java
    steps:
      - uses: actions/checkout@v3
      - uses: AbsaOSS/k3d-action@v2
        name: "Create fluvio k3d Cluster"
        with:
          cluster-name: "fluvio"
      - name: Sleep 20 to ensure k3d cluster is ready
        run: sleep 20
      - name: Install Fluvio Local Cluster
        uses: infinyon/fluvio@master
        with:
          cluster-type: local
          version: latest

      # Ensure cluster is started
      - name: Ensure Fluvio Cluster is up
        run: |
          fluvio version
          fluvio topic list
          fluvio topic create foobar
          sleep 30
          echo foo | fluvio produce foobar
          fluvio consume foobar -o 0 -d
          fluvio topic delete foobar;

      # Run docker build
      - name: Build and test clients
        run: |
          cd code/${{ matrix.client-type }}
          docker-compose build
          docker-compose run example


