name: CI

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - staging
      - trying
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  diff_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.97.3"
          extended: true

      # Checkout and build files of a base ref.
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base
      # Checkout and build files of a head ref.
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          clean: false # Prevent removing files in 'path/to/base' folder.
          path: pr

      # Build sites
      - run: |
          hugo \
            --source base \
            --destination current_site \
            --verbose \
            --cleanDestinationDir \
            --disableFastRender \
            --buildDrafts \
            --buildFuture \
            --ignoreCache

          hugo \
            --source pr \
            --destination pr_site \
            --verbose \
            --cleanDestinationDir \
            --disableFastRender \
            --buildDrafts \
            --buildFuture \
            --ignoreCache

      # Capture page differences.
      - id: diffpages
        uses: ssowonny/diff-pages-action@v1
        with:
          base-path: "current_site"
          head-path: "pr_site"

      # This example step is for uploading the result as an artifact. The result or
      # the artifact can be uploaded to the pull request comments, Amazon S3, or
      # any place according to the github action settings.
      - uses: actions/upload-artifact@v1
        with:
          name: diff-pages-artifact
          path: "${{ steps.diffpages.outputs.path }}"
