
name: 

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - staging
      - trying
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  examples:
    name: Run all client examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client-type:
          - rust
          - python
          - node
          - java
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.2'
          extended: true
      - name: Build
        run: hugo -v
      - name: Save hugo build 
        uses: actions/upload-artifact@v3
        with:
          name: hugo build 
          path: public
          retention-days: 14
