name: Hugo HTML lint

permissions:
  contents: read

concurrency:
  group: html-lint-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - staging
      - trying
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  htmltest:
    runs-on: ubuntu-latest
    name: Run htmltest to lint Hugo output
    steps:
      - name: Get PR Number
        if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
        run: |
          echo "PR_NUMBER=$(git show --oneline -s HEAD | | sed -n 's/.*(#\(.*\))$/\1/p')" >> $GITHUB_ENV

      - name: Get PR Number
        if: github.event_name != 'push' && github.ref != 'refs/heads/staging'
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Check PR Labels
        id: skip_label_check
        uses: paul1k/check-pr-labels@v1.0.0
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pull-number: ${{ env.PR_NUMBER }}
        labels: '["CI:bors-skip-html-lint"]'

      - name: Checkout code
        if: ${{ !steps.skip_label_check.outputs.result }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Hugo
        if: ${{ !steps.skip_label_check.outputs.result }}
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.97.3'
          extended: true
      - name: Run Hugo in the background
        if: ${{ !steps.skip_label_check.outputs.result }}
        run: ./hugo-start.sh &
      - name: Run htmltest
        if: ${{ !steps.skip_label_check.outputs.result }}
        run: |
          make htmltest

  # Job that follows the success of all required jobs in this workflow.
  # Used by Bors to detect that all required jobs have completed successfully
  done:
    name: Pass html lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: htmltest
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo "Done!"
