name: Hugo HTML lint

permissions:
  contents: read

concurrency:
  group: html-lint-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - staging
      - trying
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  htmltest:
    runs-on: ubuntu-latest
    name: Run htmltest to lint Hugo output
    steps:
      - name: Skip label check
        id: skip_label_check
        uses: agilepathway/label-checker@v1.2.6
        with:
          all_of: CI:bors-skip-html-lint
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          allow_failure: true

      - name: Checkout code
        if: steps.skip_label_check.outputs.label_check == 'failure'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Hugo
        if: steps.skip_label_check.outputs.label_check == 'failure'
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.97.3'
          extended: true
      - name: Run Hugo in the background
        run: ./hugo-start.sh &
      - name: Run htmltest
        run: |
          make htmltest

  # Job that follows the success of all required jobs in this workflow.
  # Used by Bors to detect that all required jobs have completed successfully
  done:
    name: Pass html lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: htmltest
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo "Done!"
