name: Hugo HTML lint

permissions:
  contents: read

concurrency:
  group: html-lint-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - staging
      - trying
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test-skip-check:
    uses: ./.github/workflows/skip-test-check.yml
    permissions:
      pull-requests: read
    with:
      labels: '["CI:bors-skip-html-lint"]'
    secrets: inherit

  htmltest:
    if: ${{ false }}
    runs-on: ubuntu-latest
    name: Run htmltest to lint Hugo output
    needs: test-skip-check
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1.2.1

      - name: Checkout code
        if: ${{ needs.test-skip-check.outputs.no-skip }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Hugo
        if: ${{ needs.test-skip-check.outputs.no-skip }}
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.97.3'
          extended: true
      - name: Run Hugo in the background
        if: ${{ needs.test-skip-check.outputs.no-skip }}
        run: ./hugo-start.sh &
      - name: Run htmltest
        if: ${{ needs.test-skip-check.outputs.no-skip }}
        run: |
          make htmltest

  # Job that follows the success of all required jobs in this workflow.
  # Used by Bors to detect that all required jobs have completed successfully
  done:
    name: Pass html lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: htmltest
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo "Done!"
