# Generates a PR that syncs stable to master
name: Sync Master to Stable
on:
  workflow_dispatch:

jobs:
  generate_sync_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Generate PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/sync-master-to-stable.sh
